# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-09 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20200909_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='class_list',
            field=models.ManyToManyField(blank=True, null=True, to='sales.ClassList', verbose_name='已报班级'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='class_type',
            field=models.CharField(choices=[('fulltime', '脱产班'), ('online', '网络班'), ('weekend', '周末班')], default='fulltime', max_length=64, verbose_name='班级类型'),
        ),
    ]
