# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-09 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20200909_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='class_list',
            field=models.ManyToManyField(blank=True, to='sales.ClassList', verbose_name='已报班级'),
        ),
    ]
