# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-10 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20200909_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('signed', '已报名'), ('unsigned', '未报名'), ('studying', '学习中'), ('paid_in_full', '交全学费')], default='unsigned', help_text='选择客户此时的状态', max_length=64, verbose_name='状态'),
        ),
    ]
