# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-12 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20200912_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultrecord',
            options={'verbose_name': '跟进记录表', 'verbose_name_plural': '跟进记录表'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部门表', 'verbose_name_plural': '部门表'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': '报名表', 'verbose_name_plural': '报名表'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='depart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.Department'),
        ),
    ]
