# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-16 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20200916_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserecord',
            options={'verbose_name': '课程记录表', 'verbose_name_plural': '课程记录表'},
        ),
        migrations.AlterModelOptions(
            name='studyrecord',
            options={'verbose_name': '学习记录表', 'verbose_name_plural': '学习记录表'},
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='course_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.CourseRecord', verbose_name='某节课程'),
        ),
    ]
